name: CI

on: [push]

jobs:
  build:

    runs-on: node:12-alpine

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: install dependencies
      run: |
        yarn
