name: TestAndBuild

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          yarn
      - name: lint
        run: |
          yarn lint
      - name: prettier
        run: |
          yarn prettier -c ./src/**/*.ts
      - name: test
        run: |
          yarn test
      - name: build project
        run: |
          yarn build
